---
title: "Feature importance"
author: "Stefano Pellegrini"
date: "12/16/2020"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
#FILENAME <- "lgb2_importance_150_ext_101_core_timepoint_0_merged.csv"
FILENAME <- "lgb2_importance_pos_neg_shift_timepoint_0_merged.csv"
DIRECTORY <- "../Plots/feature_importance/"
ATAC_BP_EXT <- 150
len_vec <- ATAC_BP_EXT * 2 + 1
 
# Load files

lgb_importance <- read.csv(paste0("../Data/ML_output/feature_importance/", FILENAME))
```


# Feature importance for concatenate strands (vector of length 602)

```{r}
# Plot the feature importance for contatenated strands
format_importance <- function(peaks_profile_df){
  as_tibble(peaks_profile_df) %>% select(feature, average) %>%
  mutate(pos = c(-ATAC_BP_EXT:ATAC_BP_EXT, -ATAC_BP_EXT:ATAC_BP_EXT), strand = c(rep("+", len_vec), rep("-", len_vec))) %>% 
  rename(score = average) %>% relocate(score, .after = strand) %>%
  mutate(score = ifelse(strand == "-", -score, score) / max(abs(score)))
}

lgb_importance_to_plot <- format_importance(lgb_importance)
 
# Distribution
lgb_importance_to_plot %>% ggplot(aes(x = pos, y = score, fill = strand)) + 
  geom_bar(stat="identity", color="black") +
  labs(title = "LGBM feature importance (concatenated strands score)",  
       x = "Feature (relative position to ATAC mid peaks)", y = "Importance") + 
  # geom_smooth(se=FALSE, size=0.6) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 20)) +
  coord_cartesian(xlim = c(-ATAC_BP_EXT+10, ATAC_BP_EXT-10)) + theme_bw() + 
  theme(text=element_text(size=19)) -> plot_lgb_importance
 plot_lgb_importance
 ggsave(paste(DIRECTORY, "lgb_feature_importance_", FILENAME, ".png", sep=""), 
        plot_lgb_importance, 
        height = 5, width=15, dpi = 300) 
 
# Most important features
lgb_importance_to_plot %>% mutate(feature = paste(pos, " (", strand, ")", sep="")) %>%
  mutate(score = abs(score)) %>% arrange(desc(score)) %>% head(20) %>% 
  arrange(score) %>% mutate(row = row_number()) %>%
  ggplot(aes(x = reorder(feature, row), y = score, fill = strand)) + 
  geom_bar(stat="identity", color="black") + 
  labs(title = "LGBM top 20 features (avg over CV)",  
       x = "Feature", y = "Score") + 
  coord_flip() + theme_bw() -> plot_lgb_importance_top20
 plot_lgb_importance_top20
 ggsave(paste(DIRECTORY, "lgb_feature_importance_top20_", FILENAME, ".png", sep=""), 
        plot_lgb_importance_top20, height = 5, width=4, dpi = 300) 
```


# Feature importance for subtracted strands (vector of length 301)

```{r}
# Plot the feature importance for subtracted strands
as_tibble(lgb_importance) %>% select(feature, average) %>% 
  mutate(feature = as.numeric(gsub("[a-zA-Z]", "", feature)),
         average = average / max(average)) -> lgb_importance_to_plot

# Distribution
lgb_importance_to_plot %>% ggplot(aes(x = feature, y = average)) + 
  geom_bar(stat="identity", color="black", fill="deepskyblue") +
  labs(title = "LGBM feature importance (subtracted strands score)",  
       x = "Feature (relative position to ATAC mid peaks)", y = "Importance") + 
  scale_x_continuous(breaks = scales::pretty_breaks(n = 20)) +
  coord_cartesian(xlim = c(-ATAC_BP_EXT+10, ATAC_BP_EXT-10)) + theme_bw() + 
  theme(text=element_text(size=19)) -> plot_lgb_importance
 plot_lgb_importance
 ggsave(paste(DIRECTORY, "lgb_feature_importance_", FILENAME, ".png", sep=""), 
        plot_lgb_importance, 
        height = 5, width=15, dpi = 300) 
```

