---
title: "Prediction probabilities"
author: "Stefano Pellegrini"
date: "12/16/2020"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
LGBM_FILENAME1 <- "lgb2_cv_val_output_150_ext_101_core_timepoint_0_merged.csv"
CNN_FILENAME1 <- "cnn1_cv_val_output_150_ext_101_core_timepoint_0_merged.csv"
# LGBM_FILENAME1 <- "lgb2_cv_val_output_150_ext_101_core_timepoint_0_merged_subtnorm.csv"
# CNN_FILENAME1 <- "cnn1_cv_val_output_150_ext_101_core_timepoint_0_merged_subtnorm.csv"

PATH <- "../Plots/predicted_probabilities/"
OUTPUT_FILENAME <- "output_pos_neg_shift_timepoint_0_merged"

DIRECTORY <- "../Plots/"
ATAC_BP_EXT <- 150
len_vec <- ATAC_BP_EXT * 2 + 1
 
# Load files
lgb_output1 <- read.csv(paste0("../Data/ML_output/predictions/", LGBM_FILENAME1))
cnn_output1 <- read.csv(paste0("../Data/ML_output/predictions/", CNN_FILENAME1))

dim(lgb_output1)
dim(cnn_output1)
```


# Plots

```{r}
# Merge the predictions into a single df
lgb_output1 %>% mutate(model = "LGBM") -> lgb_output1_to_plot
cnn_output1 %>% mutate(model = "CNN") -> cnn_output1_to_plot
output1 <- rbind(lgb_output1_to_plot, cnn_output1_to_plot) %>% 
  mutate(ypred=paste("Pred", ypred), ytrue=paste("True", ytrue)) 

# Fraction (multiply by 2 because the count is for both models)
output1 %>% ggplot() + 
  geom_histogram(aes(x = yprob, y=..count../sum(..count..)*2, 
                     fill=..count../sum(..count..)*2), bins = 20, color="black") +
  #geom_density(aes(x = yprob, y=..count../sum(..count..)), color="red") +
  labs(title = "Predicted probability distribution (fraction)",  
       x = "Predicted probability of class 1", y = "Model's fraction of predictions") + 
  # geom_smooth(se=FALSE, size=0.6) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) + 
  coord_cartesian(ylim = c(0, 0.25)) +
  scale_fill_gradient("Fraction", low = "deepskyblue", high = "red") +
  theme_bw() + 
  facet_wrap(~model) + 
  theme(text=element_text(size=19)) -> plot1
plot1
path = paste0(PATH, OUTPUT_FILENAME, "_pred_prob_plot1.png")
ggsave(path, plot1, height = 9, width = 20, dpi = 300)


### Negative and positive 

## Fraction

# Color classes
output1 %>% ggplot() + 
  geom_histogram(aes(x = yprob, y=..count../sum(..count..)*2, fill=as.factor(ytrue)), 
                 bins = 20, alpha=0.6, color="black", position="identity") +
  #geom_density(aes(x = yprob, y=..count../sum(..count..)), color="red") +
  labs(title = "Classes predicted probability (fraction)",  
       x = "Predicted probability of class 1", y = "Model's fraction of predictions") + 
  # geom_smooth(se=FALSE, size=0.6) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) + 
 # coord_cartesian(ylim = c(0, 0.2)) +
  scale_fill_manual("Class", values=c("#69b3a2", "#404080")) +
  theme_bw() + 
  facet_wrap(~model) + 
  theme(text=element_text(size=19)) -> plot2
plot2
path = paste0(PATH, OUTPUT_FILENAME, "_pred_prob_plot2.png")
ggsave(path, plot2, height = 9, width = 20, dpi = 300)

# Color models      <- BETTER
output1 %>% ggplot() + 
  geom_histogram(aes(x = yprob, y=..count../sum(..count..)*2, fill=model), 
                 bins = 20, alpha=0.6, color="black", position="identity") +
  #geom_density(aes(x = yprob, y=..count../sum(..count..)), color="red") +
  labs(title = "Classes predicted probability (fraction)",  
       x = "Predicted probability of class 1", y = "Model's fraction of predictions") + 
  # geom_smooth(se=FALSE, size=0.6) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) + 
 # coord_cartesian(ylim = c(0, 0.2)) +
  scale_fill_manual("Model", values=c("#69b3a2", "#404080")) +
  theme_bw() + 
  facet_wrap(~ytrue) + 
  theme(text=element_text(size=19)) -> plot3
plot3
path = paste0(PATH, OUTPUT_FILENAME, "_pred_prob_plot3.png")
ggsave(path, plot3, height = 9, width = 20, dpi = 300)


## Density

# Color classes
output1 %>% ggplot()  + 
  geom_density(aes(x = yprob, fill=as.factor(ytrue)), color="black", alpha=0.6) +
  labs(title = "Classes predicted probability (density)",  
       x = "Predicted probability of class 1", y = "Density") + 
  # geom_smooth(se=FALSE, size=0.6) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) + 
 # coord_cartesian(ylim = c(0, 0.2)) +
  scale_fill_manual("Class", values=c("#69b3a2", "#404080")) +
  theme_bw() + 
  facet_wrap(~model) + 
  theme(text=element_text(size=19)) -> plot4
plot4
path = paste0(PATH, OUTPUT_FILENAME, "_pred_prob_plot4.png")
ggsave(path, plot4, height = 9, width = 20, dpi = 300)

# Color models      <- BETTER
output1 %>% ggplot()  + 
  geom_density(aes(x = yprob, fill=model), color="black", alpha=0.6) +
  labs(title = "Classes predicted probability (density)",  
       x = "Predicted probability of class 1", y = "Density") + 
  # geom_smooth(se=FALSE, size=0.6) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) + 
 # coord_cartesian(ylim = c(0, 0.2)) +
  scale_fill_manual("Model", values=c("#69b3a2", "#404080")) +
  theme_bw() + 
  facet_wrap(~ytrue) + 
  theme(text=element_text(size=19)) -> plot5
plot5
path = paste0(PATH, OUTPUT_FILENAME, "_pred_prob_plot5.png")
ggsave(path, plot5, height = 9, width = 20, dpi = 300)


### False, true, positive and negative

# Fraction
output1 %>% ggplot() + 
  geom_histogram(aes(x = yprob, y=..count../sum(..count..)*2, fill=model), 
                 bins = 20, alpha=0.6, color="black", position="identity") +
  #geom_density(aes(x = yprob, y=..count../sum(..count..)), color="red") +
  labs(title = "TP, TN, FP, FN predicted probability (fraction)",  
       x = "Predicted probability of class 1", y = "Model's fraction of predictions") + 
  # geom_smooth(se=FALSE, size=0.6) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) + 
 # coord_cartesian(ylim = c(0, 0.2)) +
  scale_fill_manual("Model", values=c("#69b3a2", "#404080")) +
  theme_bw() + 
  facet_grid(vars(ytrue), vars(ypred)) + 
  theme(text=element_text(size=19)) -> plot6
plot6
path = paste0(PATH, OUTPUT_FILENAME, "_pred_prob_plot6.png")
ggsave(path, plot6, height = 9, width = 20, dpi = 300)

# Density
output1 %>% ggplot()  + 
  geom_density(aes(x = yprob, fill=model), color="black", alpha=0.6) +
  labs(title = "Classes predicted probability (density)",  
       x = "Predicted probability of class 1", y = "Density") + 
  # geom_smooth(se=FALSE, size=0.6) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) + 
 # coord_cartesian(ylim = c(0, 0.2)) +
  scale_fill_manual("Model", values=c("#69b3a2", "#404080")) +
  theme_bw() + 
  facet_grid(vars(ytrue), vars(ypred)) + 
  theme(text=element_text(size=19)) -> plot7
plot7
path = paste0(PATH, OUTPUT_FILENAME, "_pred_prob_plot7.png")
ggsave(path, plot7, height = 9, width = 20, dpi = 300)
```



