---
title: "Just plot profiles"
author: "Stefano Pellegrini"
date: "4/6/2021"
output: html_document
---


# Load packages and functions

```{r results="hide",message=FALSE, warning=FALSE}
library(rtracklayer)
library(tidyverse)
library(ggforce)
library(GenomicRanges)
library(reshape2)
library(RColorBrewer)
source("main_script_thesis.R")
```


# Initialize

```{r}
# To set
ATAC_BP_EXT <- 150
EXTRACTION <- "pos_neg_shift"
OUT_DIR <- paste0("COMPLETE_", EXTRACTION, "/")
len_vec <- ATAC_BP_EXT * 2 + 1
# Input
PATH_PROFILES <- "../Data/ML_input/timepoint_0to2_all_pos_neg_shift/merged/profiles_pos_neg_shift_timepoint_0to2_all_merged.csv"
PATH_METADATA <- "../Data/ML_input/timepoint_0to2_all_pos_neg_shift/merged/metadata_pos_neg_shift_timepoint_0to2_all_merged.csv"
```


# Load data

```{r}
# Load data 
windows_metadata <- read.csv(PATH_METADATA, header = TRUE)
windows_profiles <- read.csv(PATH_PROFILES, header = TRUE) %>% select(-label)

# Split positive and negative
pos_neg_windows <- split_pos_neg(windows_profiles, windows_metadata)
pos_windows <- pos_neg_windows$pos
neg_windows <- pos_neg_windows$neg

paste("Size total windows profile:", nrow(windows_metadata))
paste("Size positive profiles:", nrow(pos_windows$metadata))
paste("Size negative profiles:", nrow(neg_windows$metadata))
```


# Plot concatenated profiles

```{r}
# Chr distribution
plot_chr_distribution(pos_windows$metadata, save=TRUE, 
                      path=paste0("../Plots/", OUT_DIR, "positive_set/pos_chr_distribution.png"))
plot_chr_distribution(neg_windows$metadata, save=TRUE, 
                      path=paste0("../Plots/", OUT_DIR, "negative_set/neg_chr_distribution.png"))

# Plot the distribution of CAGE coverage for ATAC-Seq peak relative positions
plot_cage_distribution_by_peak_position(pos_windows$profiles, save=TRUE,
                                        path=paste0("../Plots/", OUT_DIR, "positive_set/pos_cage_by_peak_pos.png"))
plot_cage_distribution_by_peak_position(neg_windows$profiles, save=TRUE,
                                        path=paste0("../Plots/", OUT_DIR, "negative_set/neg_cage_by_peak_pos.png"))

# Plot distribution of ATAC-Seq peaks CAGE total coverage (ATAC-Seq peaks number)
plot_profiles_total_score_distribution(pos_windows$profiles, save=TRUE, 
                                       path=paste0("../Plots/", OUT_DIR, "positive_set/pos_windows_total_cage_score1.png"))
plot_profiles_total_score_distribution(neg_windows$profiles, save=TRUE, 
                                       path=paste0("../Plots/", OUT_DIR, "negative_set/neg_windows_total_cage_score1.png"))

# Plot distribution of ATAC-Seq peaks CAGE total coverage (CAGE total coverage per peak)
plot_profiles_total_score_distribution_alt(pos_windows$profiles, save=TRUE, 
                                           path=paste0("../Plots/", OUT_DIR, "positive_set/pos_windows_total_cage_score2.png"))
plot_profiles_total_score_distribution_alt(neg_windows$profiles, save=TRUE, 
                                           path=paste0("../Plots/", OUT_DIR, "negative_set/neg_windows_total_cage_score2.png"))

# Plot the maximum tss score of each window
plot_max_tss_score_distribution(pos_windows$profiles, save=TRUE,
                                path=paste0("../Plots/", OUT_DIR, "positive_set/pos_max_tss_score_plot.png"))
plot_max_tss_score_distribution(neg_windows$profiles, save=TRUE,
                                path=paste0("../Plots/", OUT_DIR, "negative_set/neg_max_tss_score_plot.png"))

# Plot different chromosomes score distribution
plot_score_distribution_by_pos_by_chr(pos_windows, save=TRUE, 
                                      path=paste0("../Plots/", OUT_DIR, "positive_set/pos_windows_score_by_pos_by_chr.png"))
plot_score_distribution_by_pos_by_chr(pos_windows, save=TRUE, scales="fixed", coord_ylim=c(-100, 100),
                                      path=paste0("../Plots/", OUT_DIR, "positive_set/pos_windows_score_by_pos_by_chr_fixedAxis.png"))
plot_score_distribution_by_pos_by_chr(neg_windows, save=TRUE, 
                                      path=paste0("../Plots/", OUT_DIR, "negative_set/neg_windows_score_by_pos_by_chr.png"))
plot_score_distribution_by_pos_by_chr(neg_windows, save=TRUE, scales="fixed", coord_ylim=c(-100, 100),
                                      path=paste0("../Plots/", OUT_DIR, "negative_set/neg_windows_score_by_pos_by_chr_fixedAxis.png"))

# Plot some profiles
plot_set_profiles(pos_windows, chr="chr1", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles1.png")) 
plot_set_profiles(pos_windows, chr="chr11", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles11.png")) 
plot_set_profiles(pos_windows, chr="chr2", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles2.png")) 
plot_set_profiles(pos_windows, chr="chr3", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles3.png")) 
plot_set_profiles(pos_windows, chr="chr4", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles4.png")) 
plot_set_profiles(neg_windows, chr="chr1", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles1.png")) 
plot_set_profiles(neg_windows, chr="chr11", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles11.png")) 
plot_set_profiles(neg_windows, chr="chr2", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles2.png")) 
plot_set_profiles(neg_windows, chr="chr3", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles3.png")) 
plot_set_profiles(neg_windows, chr="chr4", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles4.png")) 
```


# Plot normalized subtracted profiles

```{r}
# Plot profiles distribution all chromosome
plot_subt_score_distribution_by_pos(pos_windows$profiles, save=TRUE,
                                    path=paste0("../Plots/", OUT_DIR, "positive_set/pos_windows_subt_score_by_pos.png"))
plot_subt_score_distribution_by_pos(neg_windows$profiles, save=TRUE,
                                    path=paste0("../Plots/", OUT_DIR, "negative_set/neg_windows_subt_score_by_pos.png"))

# Plot profiles distribution by chromosome
plot_subt_score_distribution_by_pos_by_chr(pos_windows, save=TRUE,
                                           path=paste0("../Plots/", OUT_DIR, "positive_set/pos_windows_subt_score_by_pos_by_chr.png"))
# plot_subt_score_distribution_by_pos_by_chr(pos_windows, scales="fixed", save=TRUE,
#                                            path=paste0("../Plots/", OUT_DIR, "positive_set/pos_windows_subt_score_by_pos_by_chr_fixedAxis.png"))
plot_subt_score_distribution_by_pos_by_chr(neg_windows, save=TRUE,
                                           path=paste0("../Plots/", OUT_DIR, "negative_set/neg_windows_subt_score_by_pos_by_chr.png"))
# plot_subt_score_distribution_by_pos_by_chr(neg_windows, scales="fixed", save=TRUE,
#                                            path=paste0("../Plots/", OUT_DIR, "negative_set/neg_windows_subt_score_by_pos_by_chr_fixedAxis.png"))

# Plot some profiles
plot_subt_set_profiles(pos_windows, chr="chr1", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles1.png")) 
plot_subt_set_profiles(pos_windows, chr="chr11", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles11.png")) 
plot_subt_set_profiles(pos_windows, chr="chr2", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles2.png")) 
plot_subt_set_profiles(pos_windows, chr="chr3", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles3.png")) 
plot_subt_set_profiles(pos_windows, chr="chr4", save=TRUE, path = paste0("../Plots/", OUT_DIR, "positive_set/pos_profiles4.png")) 
plot_subt_set_profiles(neg_windows, chr="chr1", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles1.png")) 
plot_subt_set_profiles(neg_windows, chr="chr11", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles11.png")) 
plot_subt_set_profiles(neg_windows, chr="chr2", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles2.png")) 
plot_subt_set_profiles(neg_windows, chr="chr3", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles3.png")) 
plot_subt_set_profiles(neg_windows, chr="chr4", save=TRUE, path = paste0("../Plots/", OUT_DIR, "negative_set/neg_profiles4.png")) 
```